'use strict';

var funBooksCtrl = angular.module('funBooksCtrl', ['ngSanitize']);

funBooksCtrl.controller('mainCtrl', [ '$rootScope', '$scope', function($rootScope,$scope) {
	$scope.pageText = "BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG BANG";
}]);
